photogram/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from photos import views

router = routers.DefaultRouter()
router.register(r'usuarios', views.UserViewSet)
router.register(r'albumes',views.AlbumViewSet)
router.register(r'fotos',views.FotoViewSet)

urlpatterns = [
    url(r'^photos/',include('photos.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/login',views.login),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

photos/urls.py
from django.conf.urls import url

from . import views

app_name = 'photos'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /albumes/
    url(r'^albumes/$', views.albumes, name='albumes'),
    # ex: /albumes/5/
    url(r'^albumes/(?P<album_id>[a-zA-Z]+)/$', views.album, name='album'),
    #ex: /crear_album/
    url(r'^crear_album/$', views.crear_album, name='crear_album'),
    # ex: /albumes/5/fotos/3
    url(r'^albumes/(?P<album_id>[a-zA-Z]+)/fotos/(?P<pk>[0-9]+)/$', views.FotoView.as_view(), name='foto'),
    url(r'^registro',views.crear_perfil,name='crear_perfil'),
    #url(r'^login', views.login,name='login')
]

photos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
@python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ciudad = models.CharField(max_length=30, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    def __str__(self):
        return self.ciudad

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)    

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

@python_2_unicode_compatible
class Albumes(models.Model):
    profile = models.ForeignKey(User, related_name='albumes', on_delete=models.CASCADE,null=True)
    nombre = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre
   
@python_2_unicode_compatible
class Foto(models.Model):
    album = models.ForeignKey(Albumes,related_name='fotos',on_delete=models.CASCADE)
    descripcion = models.CharField(max_length = 240)
    imagen = models.TextField()
    fecha_publicacion = models.DateTimeField('Fecha de Publicación')

    def fue_publicada_recientemente(self):
        ahora = timezone.now()
        return ahora - datetime.timedelta(days=1) <=self.fecha_publicacion <= ahora

    fue_publicada_recientemente.admin_order_field = 'fecha_publicacion'
    fue_publicada_recientemente.boolean = True
    fue_publicada_recientemente.short_description = '¿Publicada recientemente?'

    def __str__(self):
        return self.descripcion

photos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.status import HTTP_401_UNAUTHORIZED
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
from .serializers import UserSerializer, AlbumSerializer, FotoSerializer
from .models import Foto, Albumes

class IndexView(generic.ListView):
    template_name = 'photos/index.html'
    context_object_name = 'lista_ultimas_fotos'
    def get_queryset(self):
         return Foto.objects.filter(fecha_publicacion__lte=timezone.now()).order_by('-fecha_publicacion')[:5]
 
def albumes(request):
    albumes_usuario= Albumes.objects.all()
    context = {'albumes_usuario':albumes_usuario}
    return render(request,'photos/albumes.html',context)

def album(request,album_id): 
    return HttpResponse("Estas en el album %s." % album_id)

def crear_album(request):
    albumes_usuario= Albumes.objects.all()

    if not request.POST['album']:
        # Redisplay the question voting form.
        return render(request, 'photos/albumes.html', {
            'albumes_usuario':albumes_usuario,
            'error_message': "Debes Ingresar un nombre para el album.",
        })
    else:        
        nuevo_album = Albumes(nombre=request.POST['album'])
        nuevo_album.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('photos:albumes', args=()))

class FotoView(generic.DetailView):
    model = Foto
    template_name = 'photos/foto.html'
    def get_queryset(self):
        """
        Excluye cualquier foto que no se haya publicado todavia.
        """
        return Foto.objects.filter(fecha_publicacion__lte=timezone.now())

def crear_perfil(request):
    
    if not request.POST.get('nombreusuario'):
        # Redisplay the question voting form.
        return render(request, 'photos/registro.html', {
            'error_message': "Debes Ingresar un nombre de usuario.",
        })
    else:
        user = User.objects.create_user(username=request.POST.get('nombreusuario'), email=request.POST.get('correo'), password=request.POST.get('password'))       
        user.profile.ciudad = request.POST['ciudad']
        user.profile.fecha_nacimiento = request.POST['fecha_nacimiento']
        user.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('photos:crear_perfil', args=()))

@api_view(["POST"])
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")

    user = authenticate(username = username,password = password)
    if not user:
        return Response({'error':'Fallo el inicio de Sesion'},status=HTTP_401_UNAUTHORIZED)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({"usuario":user.pk,"token": token.key})

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    #permission_classes = (IsAuthenticated,)

class AlbumViewSet(viewsets.ModelViewSet):
    queryset = Albumes.objects.all()
    serializer_class = AlbumSerializer
    permission_classes = (IsAuthenticated,)

class FotoViewSet(viewsets.ModelViewSet):
    queryset = Foto.objects.all()
    serializer_class = FotoSerializer
    permission_classes = (IsAuthenticated,)

photos/templates/photos/albumes.html
<h1>Albumes</h1>

{% for album in albumes_usuario %}
<li><a href="{% url 'photos:album' album.nombre %}">{{ album.nombre }}</a></li>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'photos:crear_album' %}" method="post">
{% csrf_token %}
<h3>Crear Nuevo Album</h3>
<label for="album">Nombre</label>
<input type="text" name="album" id="album" placeholder="Ingrese un nombre para el nuevo album" />
    
<input type="submit" value="Crear" />
</form>

photos/templates/photos/foto.html
<h1>{{foto.descripcion}}</h1>   
<img src="data:image/png;base64,{{foto.imagen}}">

photos/templates/photos/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}">
{% if lista_ultimas_fotos %}
<ul>
{% for foto in lista_ultimas_fotos %}
    <li><a href="{% url 'photos:foto' foto.album foto.id %}">{{ foto.descripcion }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No has subido nuevas fotos.</p>
{% endif %}

photos/templates/photos/registro.html
<h1>Usuarios</h1>

{% if success_message %}<p><strong>{{ success_message }}</strong></p>{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'photos:crear_perfil' %}" method="POST">
    {% csrf_token %}
    <h3>Registro Usuarios</h3>
    <label for="nombreusuario">Nombre de Usuario</label>
    <input type="text" id="nombreusuario" name="nombreusuario" placeholder="Ingrese un nombre de usuario.">
    <label for="correo">Correo Electronico</label>
    <input type="email" id="correo" name="correo" placeholder="Ingrese un correo electronico.">
    <label for="password">Contraseña</label>
    <input type="password" id="password" name="password" placeholder="Ingrese una contraseña.">
    <label for="ciudad">Ciudad de Residencia</label>
    <input type="text" id="ciudad" name="ciudad" placeholder="Ingrese su ciudad de residencia.">
    <label for="fecha_nacimiento">Fecha Nacimineto</label>
    <input type="datetime" id="fecha_nacimiento" name="fecha_nacimiento">
    <button type="submit">Guardar</button>
</form>